name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_user}}
          password: ${{secrets.DOCKERHUB_secret}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            seishuku/kube_news:latest
            seishuku/kube_news:v${{github.run_number}}
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.k8s_config}}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          images: seishuku/kube_news:v${{github.run_number}}
          manifests: k8s/deployment.yaml
      
